# Generated by Django 5.0.6 on 2025-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
